version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app/Dockerfile
      args:
        SSH_KEY_PATH: "${SSH_PRIVATE_KEY_RELATIVE_PATH}"
    volumes:
      - ./:/var/www

    links:
      - database
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=localhost"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=127.0.0.1"
  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=80bots"
    ports:
      - "33061:3306"
  redis:
    image: redis
    ports:
      - "63791:6379"
