version: '3'
services:

  # Nginx proxy server
  # Image: https://hub.docker.com/_/nginx
  proxy:
    image: nginx
    container_name: 80bots-proxy
    restart: unless-stopped
    ports:
      - "${DOCKER_WEB_SERVER_PORT:-80}:${DOCKER_WEB_SERVER_PORT:-80}"
      - "${DOCKER_API_SERVER_PORT:-8080}:${DOCKER_API_SERVER_PORT:-8080}"
      - "${DOCKER_SOCKET_SERVER_PORT:-6001}:${DOCKER_SOCKET_SERVER_PORT:-6001}"
    environment:
      WEB_SERVER_HOST: "${DOCKER_WEB_SERVER_HOST:-localhost}"
      WEB_SERVER_PORT: "${DOCKER_WEB_SERVER_PORT:-80}"
      API_SERVER_HOST: "${DOCKER_API_SERVER_HOST:-localhost}"
      API_SERVER_PORT: "${DOCKER_API_SERVER_PORT:-8080}"
      SOCKET_SERVER_HOST: "${DOCKER_SOCKET_SERVER_HOST:-localhost}"
      SOCKET_SERVER_PORT: "${DOCKER_SOCKET_SERVER_PORT:-6001}"
    command: /bin/bash -c "envsubst < /etc/nginx/http-server.template.conf > /etc/nginx/conf.d/http-server.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./backend:/var/www
      - ./docker-compose/proxy/http-server.template.conf:/etc/nginx/http-server.template.conf
      - ./docker-compose/proxy/src:/etc/nginx/src
      - ./docker-compose/proxy/conf.d:/etc/nginx/conf.d
    links:
      - api
      - ws
      - web
    depends_on:
      - api
      - ws
      - web
    networks:
      - app-network

  # React Web Client
  # Image: ./docker-compose/web/Dockerfile
  web:
    container_name: 80bots-web
    build:
      context: ./docker-compose/web
    environment:
      NODE_ENV: "${APP_ENV:-local}"
      PORT: "8000"
      API_URL: "${API_URL}/api"
      SOCKET_URL: "${WS_URL}"
      SOCKET_AUTH_URL: "${API_URL}/broadcasting/auth"
      STRIPE_PUBLIC_KEY: "${STRIPE_PUBLIC_KEY}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      FACEBOOK_CLIENT_ID: "${FACEBOOK_CLIENT_ID}"
      SENTRY_DSN: "${SENTRY_DSN_WEB}"
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www
    networks:
      - app-network
    depends_on:
      - api
      - ws

  # API
  # Image: ./docker-compose/api/Dockerfile
  api:
    container_name: 80bots-api
    build:
      context: ./docker-compose/backend
    restart: unless-stopped
    env_file:
      - .env
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
    volumes:
      - ./backend:/var/www
      - ./docker-compose/backend/supervisor:/etc/supervisor
    networks:
      - app-network

  # Web Sockets based on Laravel Echo Server
  # Image: https://hub.docker.com/r/oanhnn/laravel-echo-server
  ws:
    image: oanhnn/laravel-echo-server
    container_name: 80bots-ws
    restart: unless-stopped
    command: start --force
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: "some-test"
      LARAVEL_ECHO_SERVER_HOST: "0.0.0.0"
      LARAVEL_ECHO_SERVER_PORT: "6001"
      LARAVEL_ECHO_SERVER_DEBUG: "${APP_DEBUG:-false}"
      REDIS_HOST: "${REDIS_HOST:-redis}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-root}"
      REDIS_PREFIX: "${REDIS_PREFIX:-master}"
      LARAVEL_ECHO_SERVER_PROTO: "http"
    volumes:
      - ./docker-compose/ws/conf.d:/app
    links:
      - redis
    depends_on:
      - redis
    networks:
      - app-network

  # Primary DB - MySQL
  # Image: https://hub.docker.com/_/mysql
  mysql:
    image: mysql:5.7
    container_name: 80bots-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_USER: "${DOCKER_MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${DOCKER_MYSQL_PASSWORD:-user}"
      MYSQL_DATABASE: "${DOCKER_MYSQL_DATABASE:-80bots}"
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose/mysql/conf.d:/etc/mysql/conf.d/
      - ./docker-compose/mysql/data:/var/lib/mysql
    networks:
      - app-network

  # Redis
  # Image: https://hub.docker.com/_/redis/
  redis:
    build:
      context: ./docker-compose/redis
    container_name: 80bots-redis
    restart: unless-stopped
    volumes:
      - ./docker-compose/redis/data:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge