#!/bin/bash

./install.sh

read_var() {
    VAR=$(grep $1 $2 | xargs)
    IFS="=" read -ra VAR <<< "$VAR"
    echo ${VAR[1]}
}

SCHEMA="https"
SUBDOMAIN="80bots"
DOMAIN="ngrok.io"
RANDOM_HASH="$(openssl rand -hex 3)"

WEB_SUBDOMAIN="web-$SUBDOMAIN-$RANDOM_HASH"
API_SUBDOMAIN="api-$SUBDOMAIN-$RANDOM_HASH"
WS_SUBDOMAIN="ws-$SUBDOMAIN-$RANDOM_HASH"

START="# AUTOGENERATED - START"
END="# AUTOGENERATED - END"

setup_env() {
    echo \ >> .env
    echo $START >> .env

# TODO: FIX ENVS
    echo "APP_URL=${SCHEMA}://${API_SUBDOMAIN}.${DOMAIN}" >> .env
    echo "REACT_URL=${SCHEMA}://${WEB_SUBDOMAIN}.${DOMAIN}" >> .env
    echo "API_URL=${SCHEMA}://${API_SUBDOMAIN}.${DOMAIN}" >> .env
    echo "WS_URL=${SCHEMA}://${WS_SUBDOMAIN}.${DOMAIN}" >> .env

    echo "WEB_SUBDOMAIN=${WEB_SUBDOMAIN}" >> .env
    echo "API_SUBDOMAIN=${API_SUBDOMAIN}" >> .env
    echo "WS_SUBDOMAIN=${WS_SUBDOMAIN}" >> .env

    echo $END >> .env
}
if [ "$(uname)" == "Darwin" ]; then
    sed -i .back "/$START/,/$END:/d" .env
    sed -i .back '${/^[[:space:]]*$/d;}' .env
    setup_env
    rm -rf .env.back
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sed -i "/$START/,/$END:/d" .env
    sed -i '${/^[[:space:]]*$/d;}' .env
    setup_env
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under 32 bits Windows NT platform
    echo "Unsupported platform" && exitt -1
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    # Do something under 64 bits Windows NT platform
    echo "Unsupported platform" && exitt -1
fi

docker-compose up --build -d

if [ "$(uname)" == "Darwin" ]; then
  open http://localhost:4040/inspect/http
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  xdg-open http://localhost:4040/inspect/http
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ] || [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
  start http://localhost:4040/inspect/http
fi

