#!/bin/bash

./install.sh

BASE_NAME="$(openssl rand -hex 3)"
SCHEMA="https"
DOMAIN=serveo.net

read_var() {
    VAR=$(grep $1 $2 | xargs)
    IFS="=" read -ra VAR <<< "$VAR"
    echo ${VAR[1]}
}

DOCKER_WEB_SERVER_HOST=$(read_var DOCKER_WEB_SERVER_HOST .env)
DOCKER_WEB_SERVER_PORT=$(read_var DOCKER_WEB_SERVER_PORT .env)
DOCKER_API_SERVER_HOST=$(read_var DOCKER_API_SERVER_HOST .env)
DOCKER_API_SERVER_PORT=$(read_var DOCKER_API_SERVER_PORT .env)
DOCKER_SOCKET_SERVER_HOST=$(read_var DOCKER_SOCKET_SERVER_HOST .env)
DOCKER_SOCKET_SERVER_PORT=$(read_var DOCKER_SOCKET_SERVER_PORT .env)

WEB_PREFIX="$BASE_NAME"
API_PREFIX="api-$BASE_NAME"
WS_PREFIX="ws-$BASE_NAME"

WEB_HOST=$WEB_PREFIX.$DOMAIN
API_HOST=$API_PREFIX.$DOMAIN
WS_HOST=$WS_PREFIX.$DOMAIN

START="# AUTOGENERATED - START"
END="# AUTOGENERATED - END"

setup_env() {
    echo \ >> .env
    echo $START >> .env

    echo "APP_URL=${SCHEMA}://${API_HOST}" >> .env
    echo "REACT_URL=${SCHEMA}://${WEB_HOST}" >> .env
    echo "API_URL=${SCHEMA}://${API_HOST}" >> .env
    echo "WS_URL=${SCHEMA}://${WS_HOST}" >> .env

    echo $END >> .env
}
if [ "$(uname)" == "Darwin" ]; then
    sed -i .back "/$START/,/$END:/d" .env
    sed -i .back '${/^[[:space:]]*$/d;}' .env
    setup_env
    rm -rf .env.back
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sed -i "/$START/,/$END:/d" .env
    sed -i '${/^[[:space:]]*$/d;}' .env
    setup_env
    echo $END >> .env
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under 32 bits Windows NT platform
    echo "Unsupported platform" && exitt -1
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
    # Do something under 64 bits Windows NT platform
    echo "Unsupported platform" && exitt -1
fi

docker-compose up --build -d proxy

# Make it possible to publish the local project https://serveo.net/#manual
# TODO: Deploy our own hosted serveo tool in order to process everything through our domain and servers

ssh \
  -R "$WEB_HOST:80":"$DOCKER_WEB_SERVER_HOST:$DOCKER_WEB_SERVER_PORT" \
  -R "$API_HOST:80":"$DOCKER_API_SERVER_HOST:$DOCKER_API_SERVER_PORT" \
  -R "$WS_HOST:80":"$DOCKER_SOCKET_SERVER_HOST:$DOCKER_SOCKET_SERVER_PORT" \
  $DOMAIN