web_addr: 0.0.0.0:4040
authtoken: "${NGROK_AUTH}"
tunnels:
  frontend:
    addr: proxy:80
    proto: http
    subdomain: "${FRONTEND_SUBDOMAIN}"
    bind_tls: true
  backend:
    addr: proxy:8080
    proto: http
    subdomain: "${BACKEND_SUBDOMAIN}"
    bind_tls: true
  ws:
    addr: proxy:6001
    proto: http
    subdomain: "${WS_SUBDOMAIN}"
    bind_tls: true